# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models

def add_language_name(apps, schema_editor):
    """
    Add correct names for default language entries
    """
    Language = apps.get_model("rw", "language")
    for language in Language.objects.all():
        if language.language_code == 'en':
            language.name = 'English'
        elif language.language_code == 'es':
            language.name = 'Spanish'
        language.save()

def add_project_language_default(apps, schema_editor):
    """
    Add English as default project language so not left blank
    """
    Project = apps.get_model("rw", "project")
    Language = apps.get_model("rw", "language")
    language = Language.objects.filter(pk=1).first()
    for project in Project.objects.all():
        if language is not None:
            project.languages.add(language)
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0017_uiitem_blank_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(related_name='languages', to='rw.Language'),
        ),
        migrations.RunPython(add_language_name),
        migrations.RunPython(add_project_language_default)
    ]
