# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0018_proj_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='maxdistance',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='mindistance',
        ),
    ]
