# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rw', '0019_remove_speaker_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='type',
            field=models.CharField(choices=[('like', 'like'), ('flag', 'flag'), ('rate', 'rate'), ('block_asset', 'block_asset'), ('block_user', 'block_user')], max_length=16),
        ),
    ]
