# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0020_add_vote_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='geo_listen_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
