# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0021_session_geo_listen_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listeninghistoryitem',
            options={'verbose_name': 'Listening History Item', 'verbose_name_plural': 'Listening History Items'},
        ),
        migrations.AlterModelOptions(
            name='localizedstring',
            options={'verbose_name': 'Localized String', 'verbose_name_plural': 'Localized Strings'},
        ),
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'verbose_name': 'Tag Category', 'verbose_name_plural': 'Tag Categories'},
        ),
        migrations.AlterModelOptions(
            name='tagrelationship',
            options={'verbose_name': 'Tag Relationship', 'verbose_name_plural': 'Tag Relationships'},
        ),
        migrations.AlterModelOptions(
            name='timedasset',
            options={'verbose_name': 'Timed Asset', 'verbose_name_plural': 'Timed Assets'},
        ),
        migrations.AlterModelOptions(
            name='uigroup',
            options={'verbose_name': 'UI Group', 'verbose_name_plural': 'UI Groups'},
        ),
        migrations.AlterModelOptions(
            name='uiitem',
            options={'verbose_name': 'UI Item', 'verbose_name_plural': 'UI Items'},
        ),
    ]
