# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 14:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0022_update_meta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='shape',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, blank=True, srid=4326),
        ),
    ]
