# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0023_asset_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='backupuri',
            field=models.URLField(blank=True),
        ),
    ]
