# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-03 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0024_speaker_backupuri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uigroup',
            options={'ordering': ('index',), 'verbose_name': 'UI Group', 'verbose_name_plural': 'UI Groups'},
        ),
        migrations.AlterModelOptions(
            name='uiitem',
            options={'ordering': ('index',), 'verbose_name': 'UI Item', 'verbose_name_plural': 'UI Items'},
        ),
    ]
