# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0026_add_projectgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgroup',
            options={'verbose_name': 'Project Group', 'verbose_name_plural': 'Project Groups'},
        ),
        migrations.AddField(
            model_name='project',
            name='description_loc',
            field=models.ManyToManyField(blank=True, related_name='description_string', to='rw.LocalizedString'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
