# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0029_envelope_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='tag_filters',
            field=models.ManyToManyField(blank=True, to='rw.Tag'),
        ),
    ]
