# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-16 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0030_add_audiotrack_tag_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='banned_duration',
            field=models.IntegerField(default=0, verbose_name='Banned Duration'),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='start_with_silence',
            field=models.BooleanField(default=False, verbose_name='Start with Silence'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='maxdeadair',
            field=models.FloatField(verbose_name='Max Silence'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='maxduration',
            field=models.FloatField(verbose_name='Min Playback Duration'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='maxfadeintime',
            field=models.FloatField(verbose_name='Max Fade In Time'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='maxfadeouttime',
            field=models.FloatField(verbose_name='Max Fade Out Time'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='maxpanduration',
            field=models.FloatField(verbose_name='Max Pan Duration'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='maxpanpos',
            field=models.FloatField(verbose_name='Max Pan Position'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='maxvolume',
            field=models.FloatField(verbose_name='Max Volume'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='mindeadair',
            field=models.FloatField(verbose_name='Min Silence'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='minduration',
            field=models.FloatField(verbose_name='Min Playback Duration'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='minfadeintime',
            field=models.FloatField(verbose_name='Min Fade In Time'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='minfadeouttime',
            field=models.FloatField(verbose_name='Min Fade Out Time'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='minpanduration',
            field=models.FloatField(verbose_name='Min Pan Duration'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='minpanpos',
            field=models.FloatField(verbose_name='Min Pan Position'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='minvolume',
            field=models.FloatField(verbose_name='Min Volume'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='repeatrecordings',
            field=models.BooleanField(default=False, verbose_name='Repeat Recordings'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='tag_filters',
            field=models.ManyToManyField(blank=True, to='rw.Tag', verbose_name='Tag Filters'),
        ),
    ]
