# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-15 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0031_add_audiotrack_client_mixing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunSQL(
                # populate default start_time and end_time for audio assets
                "UPDATE rw_asset SET start_time=0 WHERE mediatype='audio';"
                "UPDATE rw_asset SET end_time=audiolength/1000000000.0 WHERE mediatype='audio';"
        ),
    ]
