# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-16 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0035_add_audiotrack_timed_asset_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2019, 9, 16, 11, 37, 27, 513767)),
            preserve_default=False,
        ),
        migrations.RunSQL(
                # set initial updated time to created time
                "UPDATE rw_asset SET updated=created;"
        ),
    ]
