# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 18:03
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations
import rw.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0036_add_asset_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=rw.fields.ValidatedFileField(help_text='Upload file', storage=django.core.files.storage.FileSystemStorage(base_url='/rwmedia/', location='/var/www/roundware/rwmedia/'), upload_to='.'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='loc_caption',
            field=rw.fields.ValidatedFileField(help_text='Upload captions', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/rwmedia/', location='/var/www/roundware/rwmedia/'), upload_to='.'),
        ),
    ]
