# Generated by Django 3.0 on 2022-11-14 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rw', '0037_asset_file_and_loc_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='uigroup',
            name='selection_method',
            field=models.CharField(choices=[('user', 'user'), ('random_single', 'random_single'), ('random_double', 'random_double')], default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, max_length=8192),
        ),
        # these are generated automatically based on a Django upgrade, not a 
        # change in models.py
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rw.Project'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rw.TagCategory'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
