# Generated by Django 3.0 on 2022-11-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0038_add_uigroup_selection_method_asset_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uigroup',
            name='uiitem_filter',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
