# Generated by Django 3.0 on 2024-11-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0039_uiitem_filter_remove_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='rw.Speaker'),
        ),
    ]
