# Generated by Django 4.2.23 on 2024-01-01 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0040_speaker_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='speaker',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='fill_color',
            field=models.CharField(
                default='#0000FF80', 
                help_text='Hex color for polygon fill (supports alpha: #RRGGBBAA)', 
                max_length=9
            ),
        ),
        migrations.AddField(
            model_name='speaker',
            name='border_color',
            field=models.CharField(
                default='#0000FF', 
                help_text='Hex color for polygon border (supports alpha: #RRGGBBAA)', 
                max_length=9
            ),
        ),
        migrations.RunSQL(
            # Set initial created and updated times for existing speakers
            "UPDATE rw_speaker SET created=NOW(), updated=NOW() WHERE created IS NULL OR updated IS NULL;",
            reverse_sql="-- No reverse operation needed"
        ),
    ] 