services:
  roundware-db:
    image: postgis/postgis
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: round
      POSTGRES_PASSWORD: round
    ports:
      - "5432"

  roundware-dev:
    build:
      context: ..
    image: roundware-dev:latest
    ports:
      - "8888:8888"
    command: python3 -m roundware.manage runserver 0.0.0.0:8888
    environment:
      ROUNDWARE_DEBUG: "true"
      ROUNDWARE_DB_HOST: "roundware-db"
      ROUNDWARE_DB_NAME: "round"
    volumes:
      - logs:/roundware/logs
      - ..:/code
    depends_on:
      - roundware-db
volumes:
  logs: