source "https://rubygems.org"

gem "less", "~> 2.2.2"
gem "middleman", "~> 3.0.6"
gem "middleman-minify-html", "~> 3.0.0"
gem "rack-contrib", "~> 1.1.0"
gem "redcarpet", "~> 2.2.2"
# gem "kramdown", "~> 1.3.3"
# gem "rb-inotify", "~> 0.9" comment out per https://github.com/middleman/middleman/issues/1141
gem "therubyracer", "~> 0.12.0"
gem "thin", "~> 1.5.0"

group :development do
  gem "highline", "~> 1.6.15"
end
